print(" ------------------------------------------------") 
print("|                                                |")
print("|    01HelloWorld                                |")
print("|    Name : Aileen He                            |") 
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World") 