print(" ------------------------------------------------") 
print("|                                                |")
print("|    02Goodbye World                             |")
print("|    Name : Aileen He                            |") 
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World") 
input("------> Program Paused - press enter to continue")
print("Goodbye World") 