print(" ------------------------------------------------") 
print("|                                                |")
print("|    03GoodbyePerson                             |")
print("|    Name : Aileen He                            |") 
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello") 
name = input("What is your name ? ")
#Printing The Variable:#
print("Goodbye",name)